"""Interoperability stress tests: StrictDoc (.sdoc) <-> ReqIF <-> SpecIR <-> CommonSpec.

Three test classes covering two end-to-end pipelines:

  Stress Test 1 — TestSDocToCommonSpec (10 tests):
    Real StrictDoc L2 requirements (.sdoc) -> strictdoc export -> ReqIF
    -> SpecIR import -> decompile -> CommonSpec
    Uses the actual StrictDoc project's high-level requirements (179 UIDs,
    53 sections).  External parent relations (to L1/ZEP/DO178 UIDs) are
    stripped programmatically before export.

  Stress Test 2a — TestEngineeringReqIFRoundTrip (9 tests):
    Engineering DB (SRS) -> export_reqif -> ReqIF -> SpecIR reimport
    -> decompile -> CommonSpec

  Stress Test 2b — TestEngineeringSDocInterop (7 tests):
    Engineering DB (SRS) -> export_reqif -> ReqIF -> strictdoc import
    -> .sdoc validation

Stress Test 1 requires StrictDoc (pip install strictdoc).
Stress Test 2 additionally requires the engineering docs database.

Artifacts are persisted under tests/fixtures/interop/ for inspection:

  sdoc_to_commonspec/
    input/*.sdoc                  StrictDoc L2 .sdoc (external refs stripped)
    reqif/*.reqif                 ReqIF exported by StrictDoc
    commonspec/*.md               CommonSpec decompiled from SpecIR

  engineering_round_trip/
    reqif/srs.reqif               ReqIF exported from engineering DB
    commonspec/*.md               CommonSpec decompiled after round-trip

  engineering_sdoc/
    sdoc/*.sdoc                   .sdoc files generated by StrictDoc from our ReqIF
"""
from __future__ import annotations

import glob
import os
import re
import shutil
import sqlite3
import subprocess
import unittest

from reqif.parser import ReqIFParser
from reqif.specir.decompiler import decompile
from reqif.specir.exporter import export_reqif
from reqif.specir.importer import import_reqif

# ── Paths ─────────────────────────────────────────────────────────────────

_FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "interop")

_STRICTDOC_DOCS_DIR = os.path.join(_FIXTURES_DIR, "strictdoc_docs")

_STRICTDOC_L2 = os.path.join(
    _STRICTDOC_DOCS_DIR,
    "strictdoc_21_l2_high_level_requirements.sdoc",
)

_ENGINEERING_DB = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        "..", "..", "..", "..", "..", "..",
        "docs", "engineering_docs", "build", "specir.db",
    )
)


def _clean_dir(path):
    """Remove and recreate a directory so artifacts are always fresh."""
    if os.path.exists(path):
        shutil.rmtree(path)
    os.makedirs(path)


# ── StrictDoc availability ────────────────────────────────────────────────

def _has_strictdoc():
    try:
        r = subprocess.run(
            ["strictdoc", "--version"],
            capture_output=True, text=True, timeout=15,
        )
        return r.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


_HAVE_STRICTDOC = _has_strictdoc()


# ── StrictDoc CLI wrappers ────────────────────────────────────────────────

def _strictdoc_export(input_dir, output_dir):
    r = subprocess.run(
        ["strictdoc", "export", input_dir,
         "--formats=reqif-sdoc",
         "--output-dir", output_dir,
         "--no-parallelization"],
        capture_output=True, text=True, timeout=120,
    )
    return r.returncode, r.stdout, r.stderr


def _strictdoc_import_reqif(reqif_path, output_dir):
    r = subprocess.run(
        ["strictdoc", "import", "reqif", "p01_sdoc",
         reqif_path, output_dir],
        capture_output=True, text=True, timeout=120,
    )
    return r.returncode, r.stdout, r.stderr


# ── Helpers ───────────────────────────────────────────────────────────────

def _find_reqif_file(directory):
    files = glob.glob(os.path.join(directory, "**", "*.reqif"), recursive=True)
    return files[0] if files else None


def _find_sdoc_files(directory):
    return glob.glob(os.path.join(directory, "**", "*.sdoc"), recursive=True)


def _read_all_md(directory):
    result = {}
    for path in glob.glob(os.path.join(directory, "**", "*.md"), recursive=True):
        with open(path, encoding="utf-8") as f:
            result[os.path.relpath(path, directory)] = f.read()
    return result


def _strip_external_refs(content):
    """Remove RELATIONS entries that reference UIDs outside this document.

    Strips Parent relations to SDOC-SSS-*, ZEP-*, DO178-* and all File
    relations.  Operates only on requirement-level RELATIONS: blocks, not
    the [GRAMMAR] definition.
    """
    lines = content.split("\n")
    out = []
    in_grammar = False
    in_relations = False
    relations_had_entries = False
    relations_start_idx = None

    i = 0
    while i < len(lines):
        line = lines[i]

        # Track grammar block (don't touch GRAMMAR relation type defs)
        if line.strip() == "[GRAMMAR]":
            in_grammar = True
        elif in_grammar and re.match(
            r"^\s*\[(REQUIREMENT|TEXT)\]$|^\s*\[\[SECTION\]\]$", line.strip()
        ):
            in_grammar = False

        if in_grammar:
            out.append(line)
            i += 1
            continue

        # Detect RELATIONS: block
        if line.strip() == "RELATIONS:":
            in_relations = True
            relations_had_entries = False
            relations_start_idx = len(out)
            out.append(line)
            i += 1
            continue

        if in_relations:
            if re.match(r"^- TYPE:\s+", line):
                rel_type = re.match(r"^- TYPE:\s+(\S+)", line).group(1)

                # Skip File relations entirely
                if rel_type == "File":
                    i += 1
                    while i < len(lines) and lines[i].strip().startswith(
                        ("VALUE:", "FORMAT:")
                    ):
                        i += 1
                    continue

                # Skip Parent relations to external UIDs
                if rel_type == "Parent" and i + 1 < len(lines):
                    val_match = re.match(
                        r"\s*VALUE:\s+(\S+)", lines[i + 1]
                    )
                    if val_match and re.match(
                        r"(SDOC-SSS|ZEP|DO178)-", val_match.group(1)
                    ):
                        i += 2
                        continue

                # Keep this relation entry
                relations_had_entries = True
                out.append(line)
                i += 1
                continue
            else:
                # End of RELATIONS block
                in_relations = False
                if not relations_had_entries:
                    del out[relations_start_idx]
                out.append(line)
                i += 1
                continue

        out.append(line)
        i += 1

    return "\n".join(out)


# =========================================================================
# Stress Test 1: Real StrictDoc .sdoc -> ReqIF -> SpecIR -> CommonSpec
# =========================================================================

@unittest.skipUnless(_HAVE_STRICTDOC, "strictdoc not installed")
@unittest.skipUnless(os.path.exists(_STRICTDOC_L2), "strictdoc L2 .sdoc not found")
class TestSDocToCommonSpec(unittest.TestCase):
    """Full pipeline: real StrictDoc L2 .sdoc -> ReqIF -> SpecIR -> CommonSpec.

    Uses StrictDoc's own high-level requirements specification (179 UIDs,
    53 sections, multiline statements, RATIONALE/COMMENT fields).

    Artifacts persisted to fixtures/interop/sdoc_to_commonspec/.
    """

    @classmethod
    def setUpClass(cls):
        base = os.path.join(_FIXTURES_DIR, "sdoc_to_commonspec")

        # Phase A: Prepare .sdoc with external refs stripped.
        with open(_STRICTDOC_L2, encoding="utf-8") as f:
            raw = f.read()
        cleaned = _strip_external_refs(raw)

        sdoc_dir = os.path.join(base, "input")
        _clean_dir(sdoc_dir)
        # strictdoc needs a strictdoc.toml in the project root
        toml_src = os.path.join(_STRICTDOC_DOCS_DIR, "strictdoc.toml")
        if os.path.exists(toml_src):
            shutil.copy2(toml_src, os.path.join(sdoc_dir, "strictdoc.toml"))
        sdoc_path = os.path.join(
            sdoc_dir, "strictdoc_21_l2_high_level_requirements.sdoc"
        )
        with open(sdoc_path, "w", encoding="utf-8") as f:
            f.write(cleaned)

        cls._sdoc_uid_count = len(
            re.findall(r"^UID: (.+)$", cleaned, re.MULTILINE)
        )
        cls._sdoc_section_count = len(
            re.findall(r"^\[\[SECTION\]\]$", cleaned, re.MULTILINE)
        )

        # Phase B: Export to ReqIF via strictdoc.
        export_dir = os.path.join(base, "strictdoc_export")
        _clean_dir(export_dir)
        rc, stdout, stderr = _strictdoc_export(sdoc_dir, export_dir)
        assert rc == 0, f"strictdoc export failed (rc={rc}):\n{stdout}{stderr}"

        src_reqif = _find_reqif_file(export_dir)
        assert src_reqif is not None, f"No .reqif file in {export_dir}"
        reqif_dir = os.path.join(base, "reqif")
        _clean_dir(reqif_dir)
        cls._reqif_path = os.path.join(reqif_dir, "sdoc_l2.reqif")
        shutil.copy2(src_reqif, cls._reqif_path)
        shutil.rmtree(export_dir)

        # Phase C: Parse ReqIF -> import into SpecIR.
        bundle = ReqIFParser.parse(cls._reqif_path)
        cls._conn = sqlite3.connect(":memory:")
        cls._spec_id = import_reqif(bundle, cls._conn)
        cls._conn.row_factory = sqlite3.Row

        cls._obj_count = cls._conn.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref = ?",
            (cls._spec_id,),
        ).fetchone()[0]
        cls._rel_count = cls._conn.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref = ?",
            (cls._spec_id,),
        ).fetchone()[0]

        # Phase D: Decompile to CommonSpec.
        decomp_dir = os.path.join(base, "commonspec")
        _clean_dir(decomp_dir)
        cls._md_files = decompile(
            cls._conn, cls._spec_id, decomp_dir, overwrite=True,
        )
        cls._md_dict = _read_all_md(decomp_dir)
        cls._md = "\n".join(cls._md_dict.values())

    @classmethod
    def tearDownClass(cls):
        cls._conn.close()

    # ── Structure tests ──────────────────────────────────────────────────

    def test_reqif_size(self):
        """Exported ReqIF should be substantial for 179 requirements."""
        size = os.path.getsize(self._reqif_path)
        self.assertGreater(size, 100_000, f"ReqIF only {size} bytes")

    def test_object_count(self):
        """SpecIR should contain at least as many objects as UIDs in the source.

        StrictDoc doesn't export TEXT nodes to ReqIF, so total objects may be
        less than UIDs + sections.  We check at least all UID'd requirements
        plus a reasonable section count survived.
        """
        self.assertGreaterEqual(
            self._obj_count, self._sdoc_uid_count,
            f"Expected >= {self._sdoc_uid_count} objects (UID count), "
            f"got {self._obj_count}",
        )

    def test_commonspec_multi_file(self):
        """Large spec should produce multiple CommonSpec files."""
        self.assertGreater(len(self._md_files), 5)

    # ── PID preservation ─────────────────────────────────────────────────

    def test_sdoc_uids_in_commonspec(self):
        """All SDOC-SRS-* UIDs should appear as @PID in CommonSpec headings."""
        pid_matches = re.findall(r"@SDOC-SRS-\d+", self._md)
        self.assertGreaterEqual(
            len(pid_matches), 100,
            f"Expected >= 100 SDOC-SRS PIDs, got {len(pid_matches)}",
        )

    # ── Content fidelity ─────────────────────────────────────────────────

    def test_no_literal_backslash_n(self):
        r"""Multiline content must not have literal \\n escape sequences."""
        for name, content in self._md_dict.items():
            self.assertNotIn(
                "\\n", content,
                f"Literal \\n found in {name}",
            )

    def test_requirement_titles_present(self):
        """Key requirement titles from the L2 spec should survive."""
        for title in ("Data model", "Requirement model", "Section model"):
            self.assertIn(title, self._md, f"Title '{title}' not found")

    def test_multiline_rationale_survives(self):
        """RATIONALE fields with numbered lists should not be truncated."""
        # SDOC-SRS-18 has a multiline RATIONALE with 1), 2), 3)
        self.assertIn("interface well with other formats", self._md)

    def test_attributes_present(self):
        """CommonSpec should have STATUS and RATIONALE attributes."""
        attr_lines = [l for l in self._md.split("\n") if l.startswith("> ")]
        status_lines = [l for l in attr_lines if l.startswith("> STATUS:")]
        self.assertGreater(len(status_lines), 50, "Expected > 50 STATUS attrs")

    def test_relations_rendered(self):
        """Self-referencing parent relations should produce [PID](@) links."""
        links = re.findall(r"\[SDOC-SRS-\d+\]\(@\)", self._md)
        self.assertGreater(len(links), 0, "No SDOC-SRS relation links found")

    def test_section_structure(self):
        """Output should have hierarchical headings (H2 + H3)."""
        h2 = sum(1 for l in self._md.split("\n") if l.startswith("## "))
        h3 = sum(1 for l in self._md.split("\n") if l.startswith("### "))
        self.assertGreater(h2, 10, f"Expected > 10 H2 headings, got {h2}")
        self.assertGreater(h3, 50, f"Expected > 50 H3 headings, got {h3}")


# =========================================================================
# Stress Test 2: Engineering docs round-trip
# =========================================================================

@unittest.skipUnless(os.path.exists(_ENGINEERING_DB), "engineering docs DB not found")
class TestEngineeringReqIFRoundTrip(unittest.TestCase):
    """ReqIF round-trip with real data: eng DB -> ReqIF -> SpecIR -> CommonSpec.

    Tests that our exporter produces valid ReqIF for a complex real-world spec
    (SRS: 90 objects, 17 types, 119 relations) and that our importer can
    re-consume it faithfully.

    Artifacts persisted to fixtures/interop/engineering_round_trip/.
    """

    @classmethod
    def setUpClass(cls):
        from reqif.unparser import ReqIFUnparser

        base = os.path.join(_FIXTURES_DIR, "engineering_round_trip")

        # Phase A: Export SRS from engineering DB to ReqIF.
        conn_src = sqlite3.connect(_ENGINEERING_DB)
        conn_src.row_factory = sqlite3.Row

        cls._orig_object_count = conn_src.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref = 'srs'"
        ).fetchone()[0]
        cls._orig_relation_count = conn_src.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref = 'srs'"
        ).fetchone()[0]

        rows = conn_src.execute(
            "SELECT title_text FROM spec_objects "
            "WHERE specification_ref = 'srs' AND type_ref = 'HLR' "
            "ORDER BY file_seq LIMIT 5"
        ).fetchall()
        cls._key_titles = [str(r[0]) for r in rows if r[0]]

        bundle_a = export_reqif(conn_src, "srs")
        conn_src.close()

        xml_a = ReqIFUnparser.unparse(bundle_a)
        reqif_dir = os.path.join(base, "reqif")
        _clean_dir(reqif_dir)
        cls._reqif_path = os.path.join(reqif_dir, "srs.reqif")
        with open(cls._reqif_path, "w", encoding="utf-8") as f:
            f.write(xml_a)
        cls._reqif_size = len(xml_a)

        # Phase B: Re-import the ReqIF into a fresh SpecIR.
        bundle_b = ReqIFParser.parse(cls._reqif_path)
        cls._conn = sqlite3.connect(":memory:")
        cls._spec_id = import_reqif(bundle_b, cls._conn)
        cls._conn.row_factory = sqlite3.Row

        cls._reimport_object_count = cls._conn.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref = ?",
            (cls._spec_id,),
        ).fetchone()[0]
        cls._reimport_relation_count = cls._conn.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref = ?",
            (cls._spec_id,),
        ).fetchone()[0]

        # Phase C: Decompile to CommonSpec.
        decomp_dir = os.path.join(base, "commonspec")
        _clean_dir(decomp_dir)
        cls._md_files = decompile(
            cls._conn, cls._spec_id, decomp_dir, overwrite=True,
        )
        cls._md_dict = _read_all_md(decomp_dir)
        cls._md = "\n".join(cls._md_dict.values())

    @classmethod
    def tearDownClass(cls):
        cls._conn.close()

    def test_reqif_size(self):
        """Exported ReqIF should be substantial for a 90-object spec."""
        self.assertGreater(self._reqif_size, 100_000,
                           f"ReqIF too small: {self._reqif_size}")

    def test_object_count_preserved(self):
        """All objects should survive the export→import round-trip."""
        self.assertEqual(self._reimport_object_count, self._orig_object_count)

    def test_relation_count_preserved(self):
        """Relations should survive the export→import round-trip.

        The DB may have duplicate relations (same source+target+type) that
        collapse to one in ReqIF, so allow a small delta.
        """
        delta = self._orig_relation_count - self._reimport_relation_count
        self.assertLessEqual(delta, 5,
                             f"Too many relations lost: {delta} "
                             f"(orig={self._orig_relation_count}, "
                             f"reimport={self._reimport_relation_count})")

    def test_key_titles_in_commonspec(self):
        """HLR titles from the SRS should appear in CommonSpec output."""
        found = sum(1 for t in self._key_titles if t in self._md)
        self.assertEqual(found, len(self._key_titles),
                         f"Missing titles: {[t for t in self._key_titles if t not in self._md]}")

    def test_commonspec_has_many_headings(self):
        h2_count = sum(1 for l in self._md.split("\n") if l.startswith("## "))
        self.assertGreaterEqual(h2_count, 10, f"Expected >= 10 H2 headings, got {h2_count}")

    def test_commonspec_has_pids(self):
        pid_matches = re.findall(r"@\S+", self._md)
        self.assertGreater(len(pid_matches), 20, "Expected > 20 @PID markers")

    def test_hierarchical_structure(self):
        has_h2 = any(l.startswith("## ") for l in self._md.split("\n"))
        has_h3 = any(l.startswith("### ") for l in self._md.split("\n"))
        self.assertTrue(has_h2, "No H2 headings")
        self.assertTrue(has_h3, "No H3 headings")

    def test_commonspec_has_attributes(self):
        """CommonSpec should have blockquote attribute lines."""
        attr_lines = [l for l in self._md.split("\n") if l.startswith("> ")]
        self.assertGreater(len(attr_lines), 5, "Expected > 5 attribute lines")

    def test_commonspec_has_relations(self):
        """CommonSpec should have relation links [target](@)."""
        links = re.findall(r"\[[\w-]+\]\(@\)", self._md)
        self.assertGreater(len(links), 0, "No relation links found")


@unittest.skipUnless(_HAVE_STRICTDOC, "strictdoc not installed")
@unittest.skipUnless(os.path.exists(_ENGINEERING_DB), "engineering docs DB not found")
class TestEngineeringSDocInterop(unittest.TestCase):
    """Validate our ReqIF is readable by StrictDoc (eng DB -> ReqIF -> .sdoc).

    Artifacts persisted to fixtures/interop/engineering_sdoc/.
    """

    @classmethod
    def setUpClass(cls):
        from reqif.unparser import ReqIFUnparser

        base = os.path.join(_FIXTURES_DIR, "engineering_sdoc")

        # Export SRS to ReqIF (reuse from round_trip if present, else generate).
        rt_reqif = os.path.join(
            _FIXTURES_DIR, "engineering_round_trip", "reqif", "srs.reqif")
        if os.path.exists(rt_reqif):
            reqif_path = rt_reqif
        else:
            conn = sqlite3.connect(_ENGINEERING_DB)
            conn.row_factory = sqlite3.Row
            bundle = export_reqif(conn, "srs")
            conn.close()
            xml = ReqIFUnparser.unparse(bundle)
            reqif_dir = os.path.join(base, "reqif")
            _clean_dir(reqif_dir)
            reqif_path = os.path.join(reqif_dir, "srs.reqif")
            with open(reqif_path, "w", encoding="utf-8") as f:
                f.write(xml)

        # Import into StrictDoc.
        sdoc_dir = os.path.join(base, "sdoc")
        _clean_dir(sdoc_dir)
        rc, stdout, stderr = _strictdoc_import_reqif(reqif_path, sdoc_dir)
        assert rc == 0, f"strictdoc import failed (rc={rc}):\n{stdout}{stderr}"

        cls._sdoc_files = _find_sdoc_files(sdoc_dir)
        cls._sdoc_content = ""
        for path in cls._sdoc_files:
            with open(path, encoding="utf-8") as f:
                cls._sdoc_content += f.read()

    def test_sdoc_files_produced(self):
        self.assertGreater(len(self._sdoc_files), 0)

    def test_sdoc_has_document_header(self):
        self.assertIn("[DOCUMENT]", self._sdoc_content)

    def test_sdoc_has_grammar(self):
        self.assertIn("[GRAMMAR]", self._sdoc_content)

    def test_sdoc_has_sections(self):
        self.assertIn("[[SECTION]]", self._sdoc_content)

    def test_sdoc_has_requirements(self):
        """StrictDoc should map HLR objects to requirement-like nodes."""
        # Count object nodes (any tag starting with [[ except SECTION)
        node_count = len(re.findall(r"\[\[[A-Z_]+\]\]", self._sdoc_content))
        self.assertGreater(node_count, 20, f"Expected > 20 nodes, got {node_count}")

    def test_sdoc_has_uids(self):
        uids = re.findall(r"^UID: .+$", self._sdoc_content, re.MULTILINE)
        self.assertGreater(len(uids), 10, f"Expected > 10 UIDs, got {len(uids)}")

    def test_sdoc_has_relations(self):
        rels = self._sdoc_content.count("RELATIONS:")
        self.assertGreater(rels, 5, f"Expected > 5 RELATIONS blocks, got {rels}")


# =========================================================================
# Stress Test 3: Edit round-trips and double round-trip stability
# =========================================================================

@unittest.skipUnless(_HAVE_STRICTDOC, "strictdoc not installed")
@unittest.skipUnless(os.path.exists(_STRICTDOC_L2), "strictdoc L2 .sdoc not found")
class TestSDocEditRoundTrip(unittest.TestCase):
    """Edit a real .sdoc, re-export via StrictDoc, verify edits in CommonSpec.

    Edits: status change, new requirement, title change.
    """

    @classmethod
    def setUpClass(cls):
        import tempfile

        with open(os.path.join(
            _FIXTURES_DIR, "sdoc_to_commonspec", "input",
            "strictdoc_21_l2_high_level_requirements.sdoc",
        )) as f:
            sdoc = f.read()

        # Edit 1: Change SDOC-SRS-18 status
        sdoc = sdoc.replace(
            "UID: SDOC-SRS-18\nSTATUS: Active",
            "UID: SDOC-SRS-18\nSTATUS: Modified", 1,
        )
        # Edit 2: Add new requirement after SDOC-SRS-26
        new_req = (
            "\n[REQUIREMENT]\nUID: SDOC-SRS-NEW\nSTATUS: Draft\n"
            "TITLE: Edit Round-Trip Fidelity\n"
            "STATEMENT: >>>\nStrictDoc shall preserve attributes and relations\n"
            "during SDoc-ReqIF-CommonSpec round-trips.\n<<<\n"
        )
        idx = sdoc.index("UID: SDOC-SRS-26")
        nxt = re.search(r"\n\[REQUIREMENT\]|\n\[\[SECTION\]\]|\n\[\[/SECTION\]\]",
                         sdoc[idx + 50:])
        pos = idx + 50 + nxt.start()
        sdoc = sdoc[:pos] + new_req + sdoc[pos:]
        # Edit 3: Change title
        sdoc = sdoc.replace("TITLE: Requirement model\n",
                            "TITLE: Requirement model (edited)\n", 1)

        cls._tmpdir = tempfile.TemporaryDirectory()
        tmp = cls._tmpdir.name
        proj = os.path.join(tmp, "proj")
        os.makedirs(proj)
        with open(os.path.join(proj, "l2.sdoc"), "w") as f:
            f.write(sdoc)
        toml = os.path.join(_STRICTDOC_DOCS_DIR, "strictdoc.toml")
        if os.path.exists(toml):
            shutil.copy2(toml, os.path.join(proj, "strictdoc.toml"))

        exp = os.path.join(tmp, "export")
        rc, stdout, stderr = _strictdoc_export(proj, exp)
        assert rc == 0, f"strictdoc export failed (rc={rc}):\n{stdout}{stderr}"

        reqif = _find_reqif_file(exp)
        assert reqif, "No .reqif produced"
        bundle = ReqIFParser.parse(reqif)
        cls._conn = sqlite3.connect(":memory:")
        cls._spec_id = import_reqif(bundle, cls._conn)
        cs = os.path.join(tmp, "cs")
        os.makedirs(cs)
        decompile(cls._conn, cls._spec_id, cs, overwrite=True)
        cls._md = "\n".join(_read_all_md(cs).values())

    @classmethod
    def tearDownClass(cls):
        cls._conn.close()
        cls._tmpdir.cleanup()

    def test_status_edit_survives(self):
        """Changed status should appear in CommonSpec output."""
        import re as _re
        lines = self._md.split("\n")
        for i, l in enumerate(lines):
            # Match exact PID (not SDOC-SRS-180 etc.)
            if l.lstrip().startswith("#") and _re.search(r"@SDOC-SRS-18\b", l):
                block = "\n".join(lines[i:i+8])
                self.assertIn("Modified", block)
                return
        self.fail("SDOC-SRS-18 heading not found")

    def test_new_requirement_pid(self):
        self.assertIn("@SDOC-SRS-NEW", self._md)

    def test_new_requirement_title(self):
        self.assertIn("Edit Round-Trip Fidelity", self._md)

    def test_title_edit_survives(self):
        self.assertIn("Requirement model (edited)", self._md)

    def test_original_content_preserved(self):
        pids = re.findall(r"@SDOC-SRS-\d+", self._md)
        self.assertGreater(len(pids), 100)


@unittest.skipUnless(os.path.exists(_ENGINEERING_DB), "engineering docs DB not found")
class TestSpecIREditRoundTrip(unittest.TestCase):
    """Edit SpecIR DB directly → export ReqIF → reimport → verify in CommonSpec."""

    @classmethod
    def setUpClass(cls):
        import tempfile
        from reqif.unparser import ReqIFUnparser

        cls._tmpdir = tempfile.TemporaryDirectory()
        tmp_db = os.path.join(cls._tmpdir.name, "edit.db")
        shutil.copy2(_ENGINEERING_DB, tmp_db)
        conn = sqlite3.connect(tmp_db)

        # Edit: change title, add object, update description
        conn.execute(
            "UPDATE spec_objects SET title_text = 'Five-Phase Lifecycle (Edited)' "
            "WHERE pid = 'HLR-PIPE-001'"
        )
        conn.execute(
            "INSERT INTO spec_objects "
            "(specification_ref, type_ref, pid, pid_prefix, pid_sequence, "
            " title_text, level, file_seq, from_file, label) "
            "VALUES ('srs','HLR','HLR-NEW-001','HLR',9999,"
            "'DB-Inserted Requirement',3,9999,'<edit>','hlr:db-inserted-requirement')"
        )
        new_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]
        conn.execute(
            "INSERT INTO spec_attribute_values "
            "(specification_ref, owner_object_id, name, raw_value, datatype, string_value) "
            "VALUES ('srs',?,'description','Added via direct DB edit','STRING',"
            "'Added via direct DB edit')", (new_id,),
        )
        conn.commit()
        conn.row_factory = sqlite3.Row

        bundle = export_reqif(conn, "srs")
        conn.close()
        xml = ReqIFUnparser.unparse(bundle)
        reqif_path = os.path.join(cls._tmpdir.name, "edit.reqif")
        with open(reqif_path, "w") as f:
            f.write(xml)

        cls._conn = sqlite3.connect(":memory:")
        cls._spec_id = import_reqif(ReqIFParser.parse(reqif_path), cls._conn)
        cs = os.path.join(cls._tmpdir.name, "cs")
        os.makedirs(cs)
        decompile(cls._conn, cls._spec_id, cs, overwrite=True)
        cls._md = "\n".join(_read_all_md(cs).values())

    @classmethod
    def tearDownClass(cls):
        cls._conn.close()
        cls._tmpdir.cleanup()

    def test_title_edit(self):
        self.assertIn("Five-Phase Lifecycle (Edited)", self._md)

    def test_new_object_pid(self):
        self.assertIn("@HLR-NEW-001", self._md)

    def test_new_object_title(self):
        self.assertIn("DB-Inserted Requirement", self._md)

    def test_new_object_description(self):
        self.assertIn("Added via direct DB edit", self._md)

    def test_original_preserved(self):
        self.assertIn("@HLR-PIPE-002", self._md)
        self.assertIn("@SF-001", self._md)


@unittest.skipUnless(os.path.exists(_ENGINEERING_DB), "engineering docs DB not found")
class TestDoubleRoundTripStability(unittest.TestCase):
    """DB → ReqIF → SpecIR → ReqIF → SpecIR: objects, relations, CommonSpec must be stable."""

    @classmethod
    def setUpClass(cls):
        from reqif.unparser import ReqIFUnparser
        import tempfile

        cls._tmpdir = tempfile.TemporaryDirectory()
        tmp = cls._tmpdir.name

        conn_orig = sqlite3.connect(_ENGINEERING_DB)
        conn_orig.row_factory = sqlite3.Row
        cls._orig_objs = conn_orig.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref='srs'"
        ).fetchone()[0]
        cls._orig_rels = conn_orig.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref='srs'"
        ).fetchone()[0]

        # Round 1
        b1 = export_reqif(conn_orig, "srs")
        conn_orig.close()
        r1_path = os.path.join(tmp, "r1.reqif")
        with open(r1_path, "w") as f:
            f.write(ReqIFUnparser.unparse(b1))

        conn_r1 = sqlite3.connect(":memory:")
        sid_r1 = import_reqif(ReqIFParser.parse(r1_path), conn_r1)
        conn_r1.row_factory = sqlite3.Row
        cls._r1_objs = conn_r1.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref=?", (sid_r1,)
        ).fetchone()[0]
        cls._r1_rels = conn_r1.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref=?", (sid_r1,)
        ).fetchone()[0]

        # Round 2
        b2 = export_reqif(conn_r1, sid_r1)
        conn_r1.close()
        r2_path = os.path.join(tmp, "r2.reqif")
        with open(r2_path, "w") as f:
            f.write(ReqIFUnparser.unparse(b2))

        conn_r2 = sqlite3.connect(":memory:")
        sid_r2 = import_reqif(ReqIFParser.parse(r2_path), conn_r2)
        conn_r2.row_factory = sqlite3.Row
        cls._r2_objs = conn_r2.execute(
            "SELECT COUNT(*) FROM spec_objects WHERE specification_ref=?", (sid_r2,)
        ).fetchone()[0]
        cls._r2_rels = conn_r2.execute(
            "SELECT COUNT(*) FROM spec_relations WHERE specification_ref=?", (sid_r2,)
        ).fetchone()[0]

        # Decompile both rounds
        cs1 = os.path.join(tmp, "cs1")
        cs2 = os.path.join(tmp, "cs2")
        os.makedirs(cs1); os.makedirs(cs2)

        conn_r1b = sqlite3.connect(":memory:")
        sid_r1b = import_reqif(ReqIFParser.parse(r1_path), conn_r1b)
        decompile(conn_r1b, sid_r1b, cs1, overwrite=True)
        conn_r1b.close()

        decompile(conn_r2, sid_r2, cs2, overwrite=True)
        conn_r2.close()

        md1 = _read_all_md(cs1)
        md2 = _read_all_md(cs2)
        cls._md_r1 = "\n".join(md1[k] for k in sorted(md1))
        cls._md_r2 = "\n".join(md2[k] for k in sorted(md2))

    @classmethod
    def tearDownClass(cls):
        cls._tmpdir.cleanup()

    def test_object_count_stable_round1(self):
        self.assertEqual(self._r1_objs, self._orig_objs)

    def test_object_count_stable_round2(self):
        self.assertEqual(self._r2_objs, self._r1_objs)

    def test_relation_count_stable(self):
        self.assertEqual(self._r2_rels, self._r1_rels)

    def test_commonspec_identical(self):
        """CommonSpec output must be byte-identical after double round-trip."""
        self.assertEqual(self._md_r1, self._md_r2)


if __name__ == "__main__":
    unittest.main()
